./install-keys/public-key/install-hotkey_1.sh
./install-keys/public-key/install-hotkey_2.sh
./install-keys/public-key/install-hotkey_3.sh
./install-keys/public-key/install-hotkey_4.sh
./install-keys/public-key/install-hotkey_5.sh
./install-keys/public-key/install-hotkey_6.sh
./install-keys/public-key/install-hotkey_7.sh
./install-keys/public-key/install-hotkey_8.sh
./install-keys/public-key/install-hotkey_9.sh
./install-keys/public-key/install-hotkey_10.sh
./install-keys/public-key/install-hotkey_11.sh
./install-keys/public-key/install-hotkey_12.sh
./install-keys/public-key/install-hotkey_13.sh
./install-keys/public-key/install-hotkey_14.sh
./install-keys/public-key/install-hotkey_15.sh
./install-keys/public-key/install-hotkey_16.sh
./install-keys/public-key/install-hotkey_17.sh
./install-keys/public-key/install-hotkey_18.sh
./install-keys/public-key/install-hotkey_19.sh
./install-keys/public-key/install-hotkey_20.sh
./install-keys/public-key/install-hotkey_21.sh
./install-keys/public-key/install-hotkey_22.sh
./install-keys/public-key/install-hotkey_23.sh
./install-keys/public-key/install-hotkey_24.sh
./install-keys/public-key/install-hotkey_25.sh
./install-keys/public-key/install-hotkey_26.sh
./install-keys/public-key/install-hotkey_27.sh
./install-keys/public-key/install-hotkey_28.sh
./install-keys/public-key/install-hotkey_29.sh
./install-keys/public-key/install-hotkey_30.sh